title: Fun with a Porpoise!
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: 'Innovate - Integrate - Motivate '
color:
  saturation: 0.2150352
  brandStrength: 0.8153457
  rhythmicContrast: 0.5267984
  brandColors:
    - '#FFFFFF'
    - '#383838'
    - '#FE8000'
    - '#9DA4B8'
    - '#A85000'
  lightness: 0.07166947
navigation:
  - name: JumbleFace
    url: 'http://jumble-face.com'
    type: external
  - name: Bible Study Tools
    url: 'http://helpmewithbiblestudy.org'
    type: external
analytics:
  google: UA-1062323-1
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/81bfca08-1e91-419a-a19e-d69c5dc5ee89.ico
name: Duccats
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/117446ea-29ea-4271-9eb3-2cc2d61ea01d.png
typography_spectrum: 0.4418212
layout_spectrum: 1
