typography_spectrum: 0.3962901
color:
  saturation: 0.2150352
  lightness: 0.07166947
  brandStrength: 0.8153457
  brandColors:
    - '#FFFFFF'
    - '#383838'
    - '#FE8000'
    - '#9DA4B8'
    - '#A85000'
  rhythmicContrast: 0.5267984
layout_spectrum: 0.760737
analytics:
  google: UA-1062323-1
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/117446ea-29ea-4271-9eb3-2cc2d61ea01d.png
name: Duccats
navigation:
  - name: JumbleFace
    url: 'http://jumble-face.com'
    type: external
  - name: Bible Study Tools
    url: 'http://helpmewithbiblestudy.org'
    type: external
  - name: About Duccats
    id: 3a8d9ece-3005-4e92-9c53-34f40bc49bb7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/81bfca08-1e91-419a-a19e-d69c5dc5ee89.ico
title: Fun with a Porpoise!
description: 'Innovate - Integrate - Motivate '
